# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bZdAtXYNFz7rIkh8DgTVV2xe6QAMTdv_
"""

import streamlit as st
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import matplotlib.pyplot as plt

# Load Iris dataset
iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = iris.target

# Train model
model = RandomForestClassifier()
model.fit(X, y)

# App title
st.title("🌸 Iris Flower Classifier")

# Sidebar for user input
st.sidebar.header("Input Features")

def get_user_input():
    sepal_length = st.sidebar.slider('Sepal Length (cm)', 4.0, 8.0, 5.1)
    sepal_width = st.sidebar.slider('Sepal Width (cm)', 2.0, 4.5, 3.5)
    petal_length = st.sidebar.slider('Petal Length (cm)', 1.0, 7.0, 1.4)
    petal_width = st.sidebar.slider('Petal Width (cm)', 0.1, 2.5, 0.2)
    features = {
        'sepal length (cm)': sepal_length,
        'sepal width (cm)': sepal_width,
        'petal length (cm)': petal_length,
        'petal width (cm)': petal_width
    }
    return pd.DataFrame(features, index=[0])

# Get user input
input_df = get_user_input()

# Prediction
prediction = model.predict(input_df)
prediction_proba = model.predict_proba(input_df)

# Show results
st.subheader('Prediction')
st.write(f"**Predicted Class:** {iris.target_names[prediction[0]]}")

st.subheader('Prediction Probabilities')
st.bar_chart(pd.DataFrame(prediction_proba, columns=iris.target_names))

st.subheader('Feature Importances')
fig, ax = plt.subplots()
ax.barh(X.columns, model.feature_importances_)
st.pyplot(fig)